zookeeper:
  image: eventuateio/eventuateio-local-zookeeper:0.20.1.RELEASE
  ports:
  - 2181:2181
  - 2888:2888
  - 3888:3888

kafka:
  image: eventuateio/eventuateio-local-kafka:0.20.1.RELEASE
  ports:
  - 9092:9092
  links:
  - zookeeper
  environment:
  - ADVERTISED_HOST_NAME=${DOCKER_HOST_IP}
  - KAFKA_HEAP_OPTS=-Xmx320m -Xms320m
  - ZOOKEEPER_SERVERS=zookeeper:2181

cdcservice:
  image: eventuateio/eventuateio-local-cdc-service:0.20.1.RELEASE
  ports:
  - 8099:8080
  links:
  - mysql
  - kafka
  - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword

mysql:
  build: ./mysql
  ports:
  - 3306:3306
  environment:
  - MYSQL_ROOT_PASSWORD=rootpassword
  - MYSQL_USER=mysqluser
  - MYSQL_PASSWORD=mysqlpw

#user-command-service:
#  extends:
#    file: docker-compose-common.yml
#    service: user-command-service
#  links:
#  - mysql
#  - kafka
#  - zookeeper
#  environment:
#    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/userservice
#    SPRING_DATASOURCE_USERNAME: root
#    SPRING_DATASOURCE_PASSWORD: rootpassword
#    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
#    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
#    EVENTUATELOCAL_CDC_DB_USER_NAME: root
#    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword

#user-query-service:
#  extends:
#    file: docker-compose-common.yml
#    service: user-query-service
#  links:
#  - mysql
#  - kafka
#  - zookeeper
#  environment:
#    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/userservice
#    SPRING_DATASOURCE_USERNAME: root
#    SPRING_DATASOURCE_PASSWORD: rootpassword
#    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
#    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
#    EVENTUATELOCAL_CDC_DB_USER_NAME: root
#    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword

#cart-command-service:
#  extends:
#    file: docker-compose-common.yml
#    service: cart-command-service
#  links:
#  - mysql
#  - kafka
#  - zookeeper
#  environment:
#    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/cartservice
#    SPRING_DATASOURCE_USERNAME: root
#    SPRING_DATASOURCE_PASSWORD: rootpassword
#    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
#    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
#    EVENTUATELOCAL_CDC_DB_USER_NAME: root
#    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword

#cart-query-service:
#  extends:
#    file: docker-compose-common.yml
#    service: cart-query-service
#  links:
#  - mysql
#  - kafka
#  - zookeeper
#  environment:
#    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/cartservice
#    SPRING_DATASOURCE_USERNAME: root
#    SPRING_DATASOURCE_PASSWORD: rootpassword
#    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
#    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
#    EVENTUATELOCAL_CDC_DB_USER_NAME: root
#    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword

product-command-service:
  extends:
    file: docker-compose-common.yml
    service: product-command-service
  links:
  - mysql
  - kafka
  - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/productservice
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: rootpassword
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword

product-query-service:
  extends:
    file: docker-compose-common.yml
    service: product-query-service
  links:
  - mysql
  - kafka
  - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/productservice
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: rootpassword
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword


store-command-service:
  extends:
    file: docker-compose-common.yml
    service: store-command-service
  links:
  - mysql
  - kafka
  - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/storeservice
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: rootpassword
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword

store-query-service:
  extends:
    file: docker-compose-common.yml
    service: store-query-service
  links:
  - mysql
  - kafka
  - zookeeper
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/storeservice
    SPRING_DATASOURCE_USERNAME: root
    SPRING_DATASOURCE_PASSWORD: rootpassword
    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    EVENTUATELOCAL_CDC_DB_USER_NAME: root
    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword

#gateway-service:
#  extends:
#    file: docker-compose-common.yml
#    service: gateway-service
#  links:
#  - mysql
#  - kafka
#  - zookeeper
#  environment:
#    SPRING_DATASOURCE_DRIVER_CLASS_NAME: com.mysql.jdbc.Driver
#    EVENTUATELOCAL_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
#    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
#    EVENTUATELOCAL_CDC_DB_USER_NAME: root
#    EVENTUATELOCAL_CDC_DB_PASSWORD: rootpassword

consoleserver:
  image: eventuateio/eventuateio-local-console:0.15.0
  links:
  - mysql
  - zookeeper
  ports:
  - 8085:8080
  environment:
    SPRING_DATASOURCE_URL: jdbc:mysql://mysql/eventuate
    SPRING_DATASOURCE_USERNAME: mysqluser
    SPRING_DATASOURCE_PASSWORD: mysqlpw
    EVENTUATELOCAL_ZOOKEEPER_CONNECTION_STRING: zookeeper:2181
    DEBUG: kafka-node:*
