DROP DATABASE IF EXISTS userservice;
DROP DATABASE IF EXISTS cartservice;
DROP DATABASE IF EXISTS productservice;
DROP DATABASE IF EXISTS storeservice;

CREATE DATABASE userservice;
CREATE DATABASE cartservice;
CREATE DATABASE productservice;
CREATE DATABASE storeservice;


USE users;

DROP TABLE IF EXISTS user;

CREATE TABLE user (
  id VARCHAR (255) PRIMARY KEY,
  username VARCHAR (255) UNIQUE NOT NULL,
  password VARCHAR (255) NOT NULL,
  deleted BOOLEAN
);


USE carts;

DROP TABLE IF EXISTS cart;
DROP TABLE IF EXISTS product;

CREATE TABLE cart (
  user_id VARCHAR (255) PRIMARY KEY,
  deleted BOOLEAN
);

CREATE TABLE product (
  barcode VARCHAR (255) PRIMARY KEY,
  name VARCHAR (255) NOT NULL,
  brand VARCHAR (255) NOT NULL,
  quantity VARCHAR (255) NOT NULL,
  user_id VARCHAR(255) NOT NULL,
  deleted BOOLEAN
);


SHOW DATABASES;
